server:
  port: 7070
  display-name: dubbo-web
  context-path: /
spring:
  dubbo:
    application:
      name: dubbo-web
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.reapal.dubbo.web
  mvc:
      view:
          prefix: /templates/
          suffix: .ftl
  freemarker:
      cache: false
      request-context-attribute: request
